# Default values for halo-mcp - Demo Hello World Application
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Application configuration
app:
  name: halo-mcp
  version: "1.0.0"
  environment: demo

# Frontend service
frontend:
  enabled: true
  replicaCount: 3
  image:
    repository: nginx
    tag: "1.25-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Backend API service
backend:
  enabled: true
  replicaCount: 2
  image:
    repository: node
    tag: "18-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Database
database:
  enabled: true
  type: postgresql
  image:
    repository: postgres
    tag: "15-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  persistence:
    enabled: false
    size: 10Gi
    accessMode: ReadWriteOnce
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Redis cache
redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: false
    size: 5Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Worker service
worker:
  enabled: true
  replicaCount: 2
  image:
    repository: busybox
    tag: "1.36"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 150m
      memory: 128Mi

# Batch jobs
jobs:
  migration:
    enabled: true
    image:
      repository: alpine
      tag: "3.18"
      pullPolicy: IfNotPresent
    schedule: "0 2 * * *"
  cleanup:
    enabled: true
    image:
      repository: alpine
      tag: "3.18"
      pullPolicy: IfNotPresent
    schedule: "0 4 * * 0"

# Monitoring (disabled by default for demo)
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false

# Security (simplified for demo)
security:
  podSecurityPolicy:
    enabled: false
  networkPolicy:
    enabled: false
  rbac:
    enabled: true

# Ingress (disabled by default for demo)
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: halo-mcp-demo.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Storage (disabled for demo - using emptyDir)
storage:
  fileStorage:
    enabled: false
    size: 20Gi
    accessMode: ReadWriteMany
  backupStorage:
    enabled: false
    size: 50Gi
    accessMode: ReadWriteOnce

# Configuration (demo values)
config:
  database:
    host: "" # Will be set to {{ include "halo-mcp.fullname" . }}-database in templates
    port: 5432
    name: "demo_db"
    username: "demo_user"
  redis:
    host: "" # Will be set to {{ include "halo-mcp.fullname" . }}-redis in templates
    port: 6379
  api:
    baseUrl: "http://halo-mcp-demo.local"
    timeout: 30
  features:
    enableMetrics: false
    enableTracing: false
    enableLogging: true

# Secrets (demo values - NOT for production)
secrets:
  database:
    password: "demo123"
  redis:
    password: "demo-redis"
  api:
    secretKey: "demo-secret-key"
    jwtSecret: "demo-jwt-secret"

# Node affinity and tolerations
nodeSelector: {}
tolerations: []
affinity: {}

# Service Account
serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1