apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "halo-mcp.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
data:
  app.yaml: |
    app:
      name: {{ .Values.app.name }}
      version: {{ .Values.app.version }}
      environment: {{ .Values.app.environment }}
      message: "Hello World from Halo MCP Demo!"
  demo.conf: |
    # Demo configuration file
    demo_mode=true
    log_level=info
    service_name=halo-mcp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "halo-mcp.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    echo "Demo: Initializing database..."
    sleep 2
    echo "Demo: Database initialized successfully"
  
  migrate.sh: |
    #!/bin/bash
    set -e
    echo "Demo: Running database migrations..."
    sleep 3
    echo "Demo: Migrations completed successfully"
  
  cleanup.sh: |
    #!/bin/bash
    set -e
    echo "Demo: Running cleanup tasks..."
    sleep 2
    echo "Demo: Cleanup completed successfully"