apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
    name: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep