{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "halo-mcp.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "halo-mcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
{{- end }}
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "halo-mcp.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "halo-mcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
{{- end }}
{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "halo-mcp.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.port }}
    protocol: TCP
    name: postgres
  selector:
    {{- include "halo-mcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  clusterIP: None
---
{{- end }}
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "halo-mcp.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}
    protocol: TCP
    name: redis
  selector:
    {{- include "halo-mcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
---
{{- end }}
# Headless service for StatefulSet
{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "halo-mcp.fullname" . }}-database-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.port }}
    protocol: TCP
    name: postgres
  selector:
    {{- include "halo-mcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}