{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "halo-mcp.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "halo-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "halo-mcp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "halo-mcp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- if .Values.security.rbac.enabled }}
      serviceAccountName: {{ include "halo-mcp.fullname" . }}-worker
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: worker
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        command: ['sh', '-c']
        args:
        - |
          echo "Demo Worker started at $(date)"
          while true; do
            echo "Demo: Processing background job at $(date)"
            sleep 30
            echo "Demo: Job completed successfully at $(date)"
            sleep 60
          done
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
        env:
        - name: WORKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEMO_MODE
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: temp
          mountPath: /tmp
      volumes:
      - name: config
        configMap:
          name: {{ include "halo-mcp.fullname" . }}-config
      - name: temp
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}